server:
  port: 1234
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinge?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimeZone=UTC
    username: root
    password: 123456

# JWT
jwt:
  secret: 1@3$.Ssd$%7^ #JWT加解密使用的密钥
  expiration: 604800   #JWT的超期限时间(秒)(60 * 60 * 24)

netty:
  websocket:
    port: 5678            # Websocket服务端口
#    ip: 0.0.0.0           # 绑定的网卡
#    max-frame-size: 10240 # 消息帧最大体积
#    path: /channel        # URI路径